### ISSUE TITLE
Figure out control through dji onboard sdk

### ISSUE THREAD

**Issue by alecGraves** [KSU-ART/Tasks#7]
- [ ] get the [onboard sdk](https://github.com/dji-sdk/Onboard-SDK-ROS) to function and use it to control our m100

**Comment by alecGraves** [comment]
Try to figure out how to run the node and control the drone. 
Also look into possible simulation suites using gazibo.
The name of the drone is the "DJI M100", if it helps.

**Comment by agent00jackson** [comment]
Just leaving some websites I found for now:
https://developer.dji.com/onboard-sdk/documentation/introduction/homepage.html
http://wiki.ros.org/dji_sdk
https://github.com/caochao39/hku_m100_gazebo

**Comment by agent00jackson** [comment]
I believe there's built in simulation software with the DJI SDK, Gazebo is not needed (I can't get that repo I linked to work anyways). Stuff has to be plugged into PC for it to work, however. Will be there tomorrow to test.

**Comment by alecGraves** [comment]
@agent00jackson ok, awesome! See ya then

**Comment by alecGraves** [comment]
Thanks, this might be revived in the future to do reinforcement learning for iarc mission 8
